version: '3'
services:
  web:
    build: ./web
    restart: always
    volumes:
      - ./web:/usr/src/app
    environment:
      PORT: 742
      MONGODB_URI: ${WEB_MONGODB_URI}
      FIREBASE_CONFIG: ${WEB_FIREBASE_CONFIG}
      JWT_SECRET: ${WEB_JWT_SECRET}
      SITE_PASSWORD: ${WEB_SITE_PASSWORD}
    command: npx nodemon -L --exec "yarn docker:start"
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ghost
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
  ghost:
    image: ghost:2.1.2-alpine
    restart: always
    volumes:
      - ghost:/var/lib/ghost
    environment:
      url: ${GHOST_BASE_URL}
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ${DB_PASS}
      database__connection__database: ghost
      mail__from: ${SMTP_EMAIL}
      mail__transport: SMTP
      mail__options__service: Mailgun
      mail__options__auth__user: ${SMTP_USER}
      mail__options__auth__pass: ${SMTP_PASS}
    depends_on:
      - db
  nginx:
    image: nginx:1.15-alpine
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - ghost
      - web

volumes:
  db:
  ghost:
